In [1]:
import sys

import MDAnalysis as mda
from MDAnalysis.analysis import dihedrals
from MDAnalysis.analysis import contacts
from statistics import mean, stdev
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# %matplotlib inline
import time
import glob
import math

sys.path.append('/home/khlee/repositories/pia-x/coupler/scripts')
from _heatmap import *


In [17]:
# testcase
#PDB="infiles/d3_gi_pd_mod.pdb"
#DCDs=glob.glob('infiles/test_d3_gi_pd_*.dcd')
#DCDs=glob.glob('infiles/test_d3_gi_pd_4.dcd')


PDB="/home/khlee/desmond/output/drd3/pd2/drd3_pd2.f2/init_ref.protein.pdb"
DCDs=glob.glob('/home/khlee/desmond/output/drd3/pd2/drd3_pd2.f2/drd3_pd2.f2_e0-2400.protein.wrapped.dcd')
u = mda.Universe(PDB, DCDs)


In [3]:
# define
# receptor
rec_chainid='R'
rec_segments=['27:57', '63:91', '100:134', '145:170', '186:218', '322:354', '362:400']
rec_labels=['TM1','TM2','TM3','TM4','TM5','TM6','TM7']
# Ga
ga_chainid='A'
ga_segments=['7:31','47:56','242:255','271:280', '296:311','329:351']
# need to refine above definition

# steal from https://www.uniprot.org/uniprot/P63096


In [4]:

# atomselection
segR_CA = u.select_atoms('protein and segid C'+rec_chainid+' and name CA and resid 27:57 or resid 63:91 or resid 100:134 or resid 145:170 or resid 186:218 or resid 322:354 or resid 362:400')
segR_I = segR_CA.moment_of_inertia()
# principal_axes
segR_UT = segR_CA.principal_axes()

# atomselection
segA_CA = u.select_atoms('protein and segid C'+ga_chainid+' and name CA')
segA_I = segA_CA.moment_of_inertia()
# principal_axes
segA_UT = segA_CA.principal_axes()


In [5]:
segA_UT

array([[ 0.78168562, -0.03601454, -0.62263195],
       [ 0.49370697, -0.57427138,  0.6530435 ],
       [ 0.38107877,  0.81787245,  0.43111905]])

In [6]:
from pylab import cross,dot,inv
# https://stackoverflow.com/questions/36409140/create-a-rotation-matrix-from-2-normals
from scipy.spatial.transform import Rotation as R
# https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.transform.Rotation.html

# given two vectors and calculate rotation matrix
def rot(U,V):
    W=cross(U,V)
    A=np.array([U,W,cross(U,W)]).T
    B=np.array([V,W,cross(V,W)]).T
    return dot(B,inv(A))

# unittest
# put this in unittest module
Va = np.array([ 1, 0, 100])
Vb = np.array([ 0, 1, 0.5])
rotM = rot(Va,Vb)
assert [Vb[i]==rotM.dot(Va)[i] for i in range(len(Va))]

In [7]:
# Va for segR
# Vb for segA
Va=segR_UT[0]+segR_UT[1]+segR_UT[2]
Vb=segA_UT[0]+segA_UT[1]+segA_UT[2]
rotM = rot(Va,Vb)
rotM2=R.from_matrix(rotM)
rotM2.as_euler('zyx', degrees=True)
#need to confirm this is right

array([-62.70551459, -41.27573391,  -1.47613562])

In [8]:
# Va for segR
# Vb for segA
Va=segR_UT[0]+segR_UT[1]+segR_UT[2]
Vb=segA_UT[0]+segA_UT[1]+segA_UT[2]
rotM = rot(Va,Vb)
rotM2=R.from_matrix(rotM)
rotM2.as_euler('xyx', degrees=True)
#need to confirm this is right

array([ 134.64677703,   69.84073661, -110.2751003 ])

In [ ]:
PDB="/home/khlee/desmond/output/drd3/pd2/drd3_pd2.f2/init_ref.protein.pdb"
DCDs=glob.glob('/home/khlee/desmond/output/drd3/pd2/drd3_pd2.f2/drd3_pd2.f2_e0-2400.protein.wrapped.dcd')

u = mda.Universe(PDB, DCDs)

In [18]:
for ts in u.trajectory:
    #print (ts)

    # atomselection
    segR_CA = u.select_atoms('protein and segid C'+rec_chainid+' and name CA and resid 27:57 or resid 63:91 or resid 100:134 or resid 145:170 or resid 186:218 or resid 322:354 or resid 362:400')
    segR_I = segR_CA.moment_of_inertia()
    # principal_axes
    segR_UT = segR_CA.principal_axes()

    # atomselection
    segA_CA = u.select_atoms('protein and segid C'+ga_chainid+' and name CA')
    segA_I = segA_CA.moment_of_inertia()
    # principal_axes
    segA_UT = segA_CA.principal_axes()

    Va=segR_UT[0]+segR_UT[1]+segR_UT[2]
    Vb=segA_UT[0]+segA_UT[1]+segA_UT[2]
    rotM = rot(Va,Vb)
    rotM2=R.from_matrix(rotM)
    rotM2.as_euler('zyx', degrees=True)
    print(rotM2.as_euler('xyx', degrees=True))
    


[ 164.7849741    33.4349781  -114.69861089]
[ 164.57353715   33.57597927 -114.22199538]
[ 164.51426508   33.73355831 -113.8803517 ]
[ 164.8526133    33.50299766 -114.65164904]
[ 164.83881544   33.46117407 -114.71058011]
[ 163.98511199   33.42882211 -113.85087743]
[ 163.64802857   33.74543809 -112.93780198]
[ 164.405455     33.8062729  -113.63554982]
[ 164.78780478   33.70340902 -114.22756636]
[ 164.81396336   33.93233507 -113.85057105]
[ 163.71503296   33.87319509 -112.78431261]
[ 163.12386628   33.64153661 -112.568166  ]
[ 163.46604767   32.94715783 -114.1402198 ]
[ 163.17408658   33.11486128 -113.53896981]
[ 163.7192894    33.25231589 -113.87694234]
[ 164.67325853   33.48726919 -114.48579605]
[ 163.40903498   33.35134186 -113.37495633]
[ 164.18156431   33.87172162 -113.28134218]
[ 162.53464766   33.32818527 -112.49770967]
[ 162.67454682   33.28929212 -112.71115594]
[ 163.71674462   33.38444898 -113.64307223]
[ 162.86137561   33.31639595 -112.85954384]
[ 162.31307477   33.30946575 -11

[ 165.04547605   33.73943874 -114.44195321]
[ 164.67911785   33.90265545 -113.75831191]
[ 164.84686951   34.02496135 -113.72176831]
[ 163.63792615   33.38198585 -113.56373567]
[ 162.97947712   32.80734382 -113.86763371]
[ 163.67140835   33.39795743 -113.57130872]
[ 162.02510551   33.05635272 -112.43831534]
[ 163.05700046   33.30820594 -113.0790959 ]
[ 164.32297642   34.05337527 -113.11128276]
[ 163.99576866   33.76229774 -113.2764756 ]
[ 164.02308447   33.25885886 -114.18943219]
[ 162.93081334   32.96750378 -113.5384861 ]
[ 163.45357698   32.9220197  -114.17074011]
[ 164.39307676   33.35260848 -114.42139727]
[ 163.85030193   33.43578557 -113.69510339]
[ 163.47170968   33.28620684 -113.55498188]
[ 163.2187449    33.8256601  -112.34581448]
[ 163.28117069   33.17017178 -113.55578523]
[ 163.48462714   33.34899376 -113.45900177]
[ 163.78367319   33.31590502 -113.8341879 ]
[ 163.0070293    33.15990947 -113.28453631]
[ 162.10515257   33.47819894 -111.79236049]
[ 162.63509512   33.83910892 -11

[ 162.02559531   32.30095105 -113.73854722]
[ 161.49117373   32.68491706 -112.52454407]
[ 162.69053035   32.23512031 -114.55139741]
[ 161.79875198   32.50091017 -113.15879347]
[ 161.2893113    32.16094455 -113.2117066 ]
[ 161.67668889   31.82343705 -114.19083823]
[ 159.81651118   31.77080956 -112.36151539]
[ 160.97456878   32.52552188 -112.26538919]
[ 162.76217228   32.34748352 -114.43341102]
[ 162.38509504   31.94872432 -114.72108964]
[ 160.82309027   32.29914178 -112.49559267]
[ 162.30981016   32.67084898 -113.39962268]
[ 161.20999081   32.09250132 -113.24626626]
[ 161.5847965    31.97765105 -113.83159779]
[ 161.5972444    32.61899453 -112.7471993 ]
[ 162.61695085   32.57303451 -113.89077496]
[ 161.90675444   32.22165704 -113.75028385]
[ 162.43200267   32.98802367 -112.97972622]
[ 161.78177969   32.93367888 -112.3976835 ]
[ 161.18640735   32.49471714 -112.53571066]
[ 162.67167913   32.85069366 -113.46834221]
[ 162.34324038   32.94743551 -112.95721214]
[ 162.82898953   32.86198402 -11

[ 162.04002328   33.57870842 -111.55126387]
[ 162.81795306   33.78055178 -112.00613172]
[ 163.49779023   34.02523384 -112.28867758]
[ 162.87660801   33.3278755  -112.85554456]
[ 161.51832255   32.94299534 -112.10982477]
[ 162.43718648   33.64550595 -111.84572475]
[ 163.573203     33.6425873  -113.03905909]
[ 164.03717399   34.08518952 -112.75176767]
[ 163.19254945   34.4021017  -111.3083059 ]
[ 163.23397841   33.85472259 -112.31092316]
[ 163.10581721   33.57437929 -112.66645132]
[ 163.68107263   33.83434581 -112.8166829 ]
[ 162.33587241   33.34769968 -112.25715498]
[ 162.35562383   33.48302621 -112.04313784]
[ 163.00823284   33.3491102  -112.95665375]
[ 164.7354922    33.40072282 -114.70556992]
[ 162.26712835   33.4590799  -111.99294574]
[ 163.19105477   33.62005471 -112.67614385]
[ 163.27336565   33.55075916 -112.8836579 ]
[ 163.09480238   33.46907804 -112.83854485]
[ 163.38867861   33.44206249 -113.19502229]
[ 163.80220099   33.8043494  -112.99736391]
[ 164.56691783   34.02802873 -11

[ 167.85076764   35.34580645 -114.62929562]
[ 167.39011916   35.4408153  -113.9438531 ]
[ 166.570717     35.02633865 -113.79669816]
[ 166.4793496    34.80641691 -114.09428358]
[ 167.77826552   34.89480388 -115.37274422]
[ 167.43627413   35.4185927  -114.03551185]
[ 166.77251687   35.34823563 -113.43354103]
[ 169.07423291   35.96224989 -114.86739723]
[ 169.3581718    35.69548543 -115.68650103]
[ 168.79154947   35.78646007 -114.87375169]
[ 167.66910317   35.19076667 -114.71043895]
[ 167.83171939   35.22485499 -114.8295234 ]
[ 167.79888407   35.1346359  -114.95786137]
[ 165.76787749   34.53505563 -113.80681049]
[ 167.65937697   35.26612188 -114.56185817]
[ 166.37373442   34.32642273 -114.84303188]
[ 166.00655666   34.45754741 -114.20546903]
[ 165.60038354   34.98680348 -112.81520292]
[ 166.67659791   34.49505071 -114.87302821]
[ 168.3996224    35.11456612 -115.66982071]
[ 167.68706522   34.81253289 -115.42056621]
[ 165.57964848   34.54067066 -113.59285369]
[ 166.36198031   34.65621003 -11

[ 169.8495525    35.18448903 -117.20118246]
[ 169.46798346   35.44177627 -116.28339875]
[ 167.84297057   35.03072537 -115.19709333]
[ 170.41207484   35.08119828 -118.04944164]
[ 169.08486837   35.31388903 -116.08131661]
[ 168.87016367   34.81809644 -116.74914777]
[ 169.81363291   35.44294968 -116.67959031]
[ 170.3193962    35.43507013 -117.28188375]
[ 169.89460633   35.77722759 -116.15033866]
[ 168.21280781   35.10217304 -115.48174628]
[ 171.09108153   35.94412547 -117.23240262]
[ 170.54602715   35.56916333 -117.29634144]
[ 169.66719151   35.02736989 -117.28081286]
[ 169.25324185   35.43216709 -116.05499876]
[ 169.4373158    34.95718022 -117.14472918]
[ 169.42074584   35.11540057 -116.83340039]
[ 169.64298647   35.39068351 -116.57963782]
[ 170.6437972    35.53752821 -117.4701318 ]
[ 169.32743755   35.53841914 -115.94296451]
[ 170.14663462   35.52632451 -116.91040596]
[ 170.41448298   35.84614554 -116.62401022]
[ 170.94007376   35.72578582 -117.4654178 ]
[ 169.24004341   35.18567603 -11

[ 168.77786709   34.41833205 -117.37581362]
[ 166.83404714   34.62413685 -114.81378956]
[ 167.98687465   34.55620919 -116.22439047]
[ 167.87101223   35.08244337 -115.13397158]
[ 168.51461493   35.0303284  -115.95462093]
[ 169.35406869   35.07175454 -116.83726608]
[ 168.57107366   35.19184869 -115.72183736]
[ 168.12292549   35.0229783  -115.52559101]
[ 168.76435023   34.96042615 -116.36689547]
[ 167.96973154   34.93107252 -115.52136229]
[ 169.33037242   34.95314343 -117.02887293]
[ 168.01697873   34.62323854 -116.1362673 ]
[ 168.88613579   35.01531394 -116.40490457]
[ 168.93943361   35.01867111 -116.45960639]
[ 168.21788067   34.89765248 -115.86200222]
[ 168.72833973   35.18149673 -115.91932074]
[ 168.48648649   35.18475809 -115.63911652]
[ 168.22945766   34.90599462 -115.85981286]
[ 169.04598866   35.13620297 -116.36488261]
[ 168.11979891   35.06885346 -115.43808069]
[ 167.99462164   35.17218816 -115.1082534 ]
[ 167.12110447   34.43195752 -115.47951117]
[ 169.3500204    35.09287625 -11

[ 169.85716574   35.93972307 -115.80364013]
[ 169.67083497   35.73221358 -115.97657786]
[ 171.27545975   36.02991098 -117.28807922]
[ 169.61246414   36.09698764 -115.22896253]
[ 171.49076262   35.97611418 -117.64476672]
[ 171.5841005    36.62402299 -116.52540763]
[ 171.00477426   35.88433497 -117.24339268]
[ 169.69958989   36.14849509 -115.23231085]
[ 169.13723395   35.36492723 -116.0467907 ]
[ 168.85941428   35.61533807 -115.26736867]
[ 168.28176225   35.28754369 -115.21923333]
[ 168.12085238   35.46640582 -114.70990088]
[ 167.95571661   35.34782135 -114.74282801]
[ 168.76723678   35.46241186 -115.44554844]
[ 169.14553987   36.00760885 -114.86387703]
[ 169.49277485   36.24669176 -114.81248898]
[ 170.65298649   36.36149203 -115.93202732]
[ 169.91538982   36.65129635 -114.53515181]
[ 169.68776071   36.57164226 -114.42537574]
[ 170.26195412   36.17526246 -115.82923058]
[ 169.32908048   35.85481754 -115.35699299]
[ 169.34952857   35.90967722 -115.27818973]
[ 170.97358956   36.11448666 -11

[ 167.80434817   35.36056778 -114.55047648]
[ 169.53586612   35.03384749 -117.11692922]
[ 169.49824851   35.01934493 -117.10028045]
[ 169.66003021   35.5630399  -116.27904315]
[ 168.99282365   35.56162729 -115.51823134]
[ 168.86851796   35.36663097 -115.73736055]
[ 169.1513149    34.99969977 -116.73718374]
[ 168.96864842   35.26296391 -116.04271616]
[ 169.28971974   35.14770094 -116.6230044 ]
[ 168.52651496   34.8806638  -116.24266006]
[ 169.19488424   35.66932885 -115.54866734]
[ 169.09146952   35.8159779  -115.15875713]
[ 168.63349238   34.86738336 -116.38865082]
[ 168.09601466   34.97642047 -115.58049424]
[ 169.24981621   35.42945355 -116.05610454]
[ 168.73244747   35.23546484 -115.82460793]
[ 170.2050019    35.39227557 -117.22823123]
[ 169.80935085   35.83383401 -115.94640963]
[ 170.79861699   35.71692276 -117.31567995]
[ 171.74701992   35.92422717 -118.0480002 ]
[ 170.9159184    36.29966363 -116.35555408]
[ 169.9530115    36.26083525 -115.31238632]
[ 169.48004882   36.13702382 -11

[ 167.00100989   35.23592224 -113.88844673]
[ 169.36440077   35.98337587 -115.15784871]
[ 169.4217885    35.99093217 -115.20919015]
[ 168.97559106   35.93617171 -114.80413969]
[ 167.45574402   35.47197153 -113.95944179]
[ 167.76675244   35.83297154 -113.64152599]
[ 168.83743507   35.7253539  -115.03881752]
[ 167.98936156   35.51769074 -114.46862843]
[ 167.9199461    35.61600596 -114.21057199]
[ 168.79226598   36.21532243 -114.07848768]
[ 169.81347608   36.37397409 -114.94007216]
[ 169.10285041   35.75894948 -115.27756625]
[ 167.23444038   35.77739939 -113.15667095]
[ 168.6061782    35.05199554 -116.01871778]
[ 168.90462733   35.73874861 -115.09007941]
[ 169.24761209   35.88662173 -115.20499581]
[ 168.28822604   35.72980002 -114.41234088]
[ 170.23270023   36.11408838 -115.91029871]
[ 168.37201287   35.1039734  -115.65806109]
[ 168.93195865   35.50086676 -115.56145773]
[ 169.00549784   35.61429225 -115.43512135]
[ 167.04635585   34.99441376 -114.37741073]
[ 168.93669249   35.88847139 -11

[ 167.8345859    35.18331939 -114.90872904]
[ 167.61459274   35.28236367 -114.48234117]
[ 168.09453231   35.54414736 -114.53751871]
[ 167.53048301   35.23469461 -114.47597075]
[ 170.23233782   35.38060965 -117.28183629]
[ 168.62543756   35.02286606 -116.09410206]
[ 168.46664744   34.7221672  -116.46489612]
[ 167.43038916   34.77715777 -115.19820189]
[ 167.1399865    34.71315658 -114.99139053]
[ 169.17370155   35.22670249 -116.34399925]
[ 167.79122523   34.95222246 -115.2824985 ]
[ 168.07501607   35.12507428 -115.28476875]
[ 166.44777927   34.5319158  -114.55469884]
[ 168.28666036   35.1856446  -115.41186039]
[ 167.93465411   35.26151752 -114.87746363]
[ 167.04349333   35.36414147 -113.70173074]
[ 167.98085574   35.31728375 -114.82694441]
[ 167.18058795   35.63290077 -113.36190313]
[ 168.57833243   35.40719106 -115.33359182]
[ 167.74423657   35.30901504 -114.57788722]
[ 167.74985423   35.25532165 -114.68240652]
[ 168.08083954   35.72233842 -114.19428663]
[ 167.8576525    35.34565219 -11

[ 169.5561623    36.41549688 -114.56860397]
[ 170.60239387   36.22847176 -116.1240927 ]
[ 169.34572434   35.92522286 -115.24490304]
[ 169.83207262   35.89220647 -115.86355698]
[ 169.35760848   36.3131542  -114.53454957]
[ 171.75605853   36.71487812 -116.55543208]
[ 170.37871752   36.64085941 -115.08666747]
[ 169.9209629    36.30599728 -115.19082478]
[ 170.54613431   36.61131627 -115.33593261]
[ 172.60304211   36.99768554 -117.022682  ]
[ 170.35484717   36.20457609 -115.8816543 ]
[ 168.59360721   35.71511517 -114.78246529]
[ 168.88050273   35.88149683 -114.79808956]
[ 168.96474031   36.06505625 -114.55231688]
[ 170.43431298   36.58727436 -115.25209146]
[ 169.01704375   35.89340799 -114.93051682]
[ 171.09434086   36.17296341 -116.80428834]
[ 169.47942116   36.12793407 -115.01923735]
[ 169.10930509   36.08955926 -114.67024158]
[ 170.33284559   36.37019046 -115.54443   ]
[ 169.28755274   36.02067332 -115.00085884]
[ 169.77215661   36.07186491 -115.45884347]
[ 169.19990726   36.04262562 -11

[ 167.14350366   35.00264025 -114.46982268]
[ 167.29671668   34.92569087 -114.7794786 ]
[ 166.80178173   34.89566809 -114.28689366]
[ 167.66409377   35.01134242 -115.03246926]
[ 168.26415406   35.64046469 -114.55009034]
[ 167.89891741   35.42672572 -114.53466738]
[ 167.70588759   35.01655902 -115.06962765]
[ 167.35104926   35.03691253 -114.63741399]
[ 168.70359128   35.13777284 -115.97166725]
[ 168.29533864   35.26307975 -115.27945829]
[ 168.06170494   35.6311009  -114.34088846]
[ 168.46365007   35.61623361 -114.81877567]
[ 167.22752571   35.35162727 -113.92718478]
[ 167.07978132   35.14896243 -114.13339814]
[ 168.52700989   35.40259344 -115.28408105]
[ 168.26906525   35.56948918 -114.68635452]
[ 168.25230321   35.70026839 -114.42658062]
[ 168.22358719   35.77485481 -114.25690586]
[ 167.23051251   35.39091938 -113.85879092]
[ 167.4135053    35.07276308 -114.64144936]
[ 168.62991963   36.05957293 -114.1854326 ]
[ 170.17267571   36.07466229 -115.91487597]
[ 167.78124313   35.43353403 -11

[ 168.0573567    35.45980359 -114.6509623 ]
[ 168.0281791    35.24651576 -115.00968659]
[ 167.98089883   35.22778327 -114.99103768]
[ 167.94804705   35.21185267 -114.98342814]
[ 169.40755199   35.70746394 -115.72070902]
[ 170.39190661   36.32440394 -115.69900642]
[ 170.1088624    36.49169161 -115.05744131]
[ 169.84018853   35.89434013 -115.86891252]
[ 168.57364311   35.59776648 -114.97675576]
[ 168.12734808   35.18908199 -115.22627181]
[ 168.80802714   35.70246638 -115.04792318]
[ 167.80184314   35.69873155 -113.9272257 ]
[ 167.92305932   36.11455793 -113.29572286]
[ 167.75231846   35.63635004 -113.98682789]
[ 168.42039267   35.66656248 -114.67727031]
[ 168.46011129   36.10720559 -113.90684146]
[ 168.7846755   36.1653032 -114.1629654]
[ 168.90538572   35.82902394 -114.92357297]
[ 166.89452342   35.52979013 -113.23655149]
[ 168.03430021   35.73182799 -114.12491615]
[ 169.9708022    36.46754617 -114.94443037]
[ 170.63778565   36.31316077 -116.0055676 ]
[ 170.94820307   36.34469405 -116.3

[ 168.56070689   35.88363012 -114.43372942]
[ 169.3635799    35.68584412 -115.71060013]
[ 170.64087599   36.4882415  -115.67849519]
[ 168.98768008   35.76797922 -115.13003162]
[ 167.8218638    35.69856023 -113.94977039]
[ 169.06740627   35.64495478 -115.44870295]
[ 170.00966647   35.69752681 -116.43208206]
[ 169.50731469   35.80085049 -115.66113137]
[ 169.09179306   35.26865786 -116.17279103]
[ 168.64522895   35.13533378 -115.90986821]
[ 168.9638291    35.14715443 -116.25081099]
[ 169.86419884   35.41399869 -116.79192646]
[ 170.05209817   35.87852706 -116.14292314]
[ 167.60597004   35.00258815 -114.98357551]
[ 167.86479057   35.16650097 -114.97327199]
[ 167.71867396   35.21540455 -114.72065141]
[ 168.62355356   35.79964615 -114.65985275]
[ 169.8205755    35.64154166 -116.31797067]
[ 170.90073707   35.9626151  -116.97368227]
[ 170.95546951   36.17161073 -116.64379642]
[ 169.52272925   35.57935365 -116.09084331]
[ 169.94089618   35.56746391 -116.59505498]
[ 170.08407488   35.96487214 -11

[ 169.47991215   36.36576471 -114.57504054]
[ 168.89323386   36.34955749 -113.94205731]
[ 168.66049243   36.72544887 -112.98043974]
[ 169.65017943   36.17868451 -115.11930077]
[ 170.9927512    37.00111964 -115.11388827]
[ 171.09330446   36.99273211 -115.24686763]
[ 170.25659214   36.90110215 -114.45398535]
[ 169.14879522   36.29995732 -114.32268062]
[ 169.30841673   36.2837011  -114.53378628]
[ 168.11495702   35.88599138 -113.93064999]
[ 168.56290657   36.02259604 -114.17879745]
[ 168.04829552   36.16825016 -113.33526942]
[ 169.27988827   36.53283502 -114.03550246]
[ 170.01609878   36.52516662 -114.88793339]
[ 169.714512     36.87845203 -113.87839107]
[ 170.92493386   36.4892379  -116.00737261]
[ 169.26609611   35.98766483 -115.03794621]
[ 168.81324388   36.05443634 -114.40113878]
[ 168.72379337   35.88324302 -114.61796827]
[ 168.42183445   36.28656396 -113.53143325]
[ 169.6170784    36.18710877 -115.06571364]
[ 169.80319942   36.56023094 -114.5784184 ]
[ 168.64892555   36.45093341 -11

[ 171.35021579   36.85127151 -115.81688567]
[ 171.50237898   37.06910489 -115.57916985]
[ 171.99209827   37.56322937 -115.20493213]
[ 171.91025721   37.24874509 -115.71452036]
[ 171.52497066   36.91980475 -115.89124573]
[ 170.22442551   36.79263755 -114.62228554]
[ 171.54085139   37.23377793 -115.30878294]
[ 170.96990503   36.75794585 -115.55002603]
[ 170.33490067   36.68775629 -114.94754242]
[ 172.53421284   37.37331079 -116.21496173]
[ 171.52768809   36.74735558 -116.22370829]
[ 171.03396422   36.90519358 -115.3445533 ]
[ 171.36476132   36.61871665 -116.27698874]
[ 170.73988956   36.50106777 -115.76931447]
[ 171.72304811   36.89034879 -116.18097915]
[ 169.84661666   36.20213555 -115.30033801]
[ 172.34458198   36.7367035  -117.21451047]
[ 170.96388274   36.87618162 -115.31820209]
[ 172.14586793   36.95601621 -116.55636529]
[ 171.24522169   36.76542036 -115.85743981]
[ 171.7897603    36.58874427 -116.83613689]
[ 170.43848393   36.28306371 -115.83084232]
[ 171.44551832   36.95371239 -11

[ 169.88514115   36.01749995 -115.69036535]
[ 169.31477993   36.15250641 -114.78598006]
[ 170.81747574   36.43942975 -115.97628083]
[ 169.5946899    36.08335787 -115.23411278]
[ 167.24264799   35.50812866 -113.65815997]
[ 168.10240499   35.26509135 -115.05887074]
[ 166.93979812   35.45315119 -113.42576372]
[ 168.60121944   35.83485964 -114.56954817]
[ 169.46957377   36.37365544 -114.54851586]
[ 169.28476396   36.1781936  -114.7039573 ]
[ 168.01792513   35.42003156 -114.6798964 ]
[ 167.71367817   35.69986663 -113.8273468 ]
[ 169.2943691    36.25316789 -114.57488845]
[ 168.79292686   36.25815145 -113.99955232]
[ 169.56709785   35.85455177 -115.62955341]
[ 168.05935671   35.81736656 -113.99525702]
[ 167.09162215   35.18002059 -114.08995125]
[ 168.60400511   35.78533467 -114.66432154]
[ 169.56644259   36.16626461 -115.0468774 ]
[ 168.40464725   35.63402101 -114.71961908]
[ 167.41723158   35.18741898 -114.43655348]
[ 167.97565135   35.40423546 -114.66162499]
[ 167.51480015   35.24774482 -11

[ 167.82057963   35.71784872 -113.91289248]
[ 169.61429773   36.36608495 -114.7274152 ]
[ 170.75262842   36.67252347 -115.45942177]
[ 171.37665281   37.05486664 -115.45907132]
[ 169.76941027   36.80475423 -114.07964823]
[ 169.52700751   36.4631534  -114.44612051]
[ 170.1329334    36.88465998 -114.34345151]
[ 170.12255803   36.11643564 -115.77860213]
[ 168.10735523   35.67881372 -114.3040381 ]
[ 169.35719681   35.94313571 -115.22461599]
[ 168.55935216   36.08044249 -114.06756769]
[ 169.47365327   35.74746653 -115.72196157]
[ 170.04333945   36.39939608 -115.15584816]
[ 170.00354922   36.75382175 -114.44262485]
[ 168.62737747   36.24835166 -113.83208622]
[ 168.20108929   36.10448788 -113.62290797]
[ 167.58155448   35.89414589 -113.32437749]
[ 168.76927612   35.90062111 -114.63703214]
[ 168.98985342   36.48897507 -113.79058278]
[ 168.68812957   36.52657279 -113.38225371]
[ 169.98294096   36.8258087  -114.28322381]
[ 168.15150962   36.20681965 -113.37844672]
[ 169.44015104   36.42087935 -11

[ 169.30187965   36.44796119 -114.21924478]
[ 168.85971809   36.29176555 -114.0120428 ]
[ 170.74595337   36.78521319 -115.23794388]
[ 169.2075485    36.49779751 -114.01936775]
[ 167.72122548   36.25304595 -112.81733364]
[ 168.7283562    36.3790308  -113.70211744]
[ 168.97699691   36.21513017 -114.28684276]
[ 170.14293284   36.62301243 -114.84906945]
[ 168.68631311   36.25519618 -113.88540301]
[ 170.16987505   36.55382223 -115.01049683]
[ 170.20745971   37.14191868 -113.94139385]
[ 169.33835148   36.87244117 -113.46439512]
[ 169.1491816    36.90217872 -113.19587432]
[ 169.89178846   37.12783798 -113.60862946]
[ 170.17563172   36.8018906  -114.54883189]
[ 170.69641554   37.15688549 -114.47409485]
[ 168.83583259   36.68928287 -113.2436673 ]
[ 168.3279028    35.77154858 -114.37973951]
[ 169.23848877   36.36041953 -114.31120918]
[ 169.49784131   36.31767821 -114.68544668]
[ 167.84228071   35.68050855 -114.00562724]
[ 168.58814511   36.24325532 -113.7976321 ]
[ 168.25301707   35.75237518 -11

[ 169.49226827   36.38612064 -114.55097092]
[ 169.32987628   36.05708025 -114.98114422]
[ 167.2118058    35.39634794 -113.82826361]
[ 167.97524084   35.58207712 -114.33455739]
[ 167.38697639   35.56897581 -113.70600594]
[ 168.48235184   36.20946308 -113.74206429]
[ 168.82209541   35.91639344 -114.66737258]
[ 167.7601079    35.81326735 -113.67040365]
[ 167.85917677   35.84707241 -113.71802476]
[ 168.31618507   35.91081932 -114.10938433]
[ 168.06359627   35.89462397 -113.85753517]
[ 169.63309785   36.49505731 -114.50695438]
[ 168.4303335    36.16024966 -113.77523033]
[ 168.07857177   36.18478655 -113.3382671 ]
[ 170.29436118   36.78844063 -114.71053306]
[ 170.76381422   37.05781445 -114.74053447]
[ 170.17447874   36.65324176 -114.82825611]
[ 168.13328798   35.99345092 -113.75269249]
[ 169.13675923   36.39662399 -114.12858459]
[ 169.44957766   36.75637368 -113.80803151]
[ 168.26250605   36.37874133 -113.18311026]
[ 168.62772201   36.65966516 -113.06669456]
[ 168.75744391   36.31181199 -11

[ 167.75837377   35.72877802 -113.82378662]
[ 167.88834405   35.77708508 -113.8792082 ]
[ 171.04305437   36.78541639 -115.58307732]
[ 170.09471814   36.43753712 -115.14313809]
[ 168.73068993   35.99001193 -114.42776166]
[ 168.00672389   36.28805449 -113.06766371]
[ 168.74122756   36.18588018 -114.07588498]
[ 168.10160072   36.20562112 -113.32527283]
[ 168.32176397   36.15951451 -113.65544974]
[ 169.10331287   36.01936915 -114.79411   ]
[ 168.26161687   36.34696931 -113.24105997]
[ 168.97936584   36.81096488 -113.1765958 ]
[ 170.22989982   36.69271965 -114.8173843 ]
[ 170.39895442   36.7744051  -114.8574205 ]
[ 169.2363528    36.78168474 -113.51996406]
[ 170.43548879   36.87277883 -114.71317946]
[ 168.78035191   36.57543328 -113.39422844]
[ 169.94285533   36.55290803 -114.75181019]
[ 168.94052004   36.52870399 -113.66095756]
[ 168.33630467   36.00113214 -113.96487514]
[ 167.8779496    36.10298891 -113.2671624 ]
[ 168.68814104   36.43401934 -113.55470337]
[ 168.77962277   36.27531836 -11

In [22]:
PDB="/home/khlee/desmond/output/drd3/pd2/drd3_pd2.f1/init_ref.protein.pdb"
DCDs=glob.glob('/home/khlee/desmond/output/drd3/pd2/drd3_pd2.f1/drd3_pd2.f1_e0-2400.protein.wrapped.dcd')

u = mda.Universe(PDB, DCDs)

In [23]:
for ts in u.trajectory:
    #print (ts)

    # atomselection
    segR_CA = u.select_atoms('protein and segid C'+rec_chainid+' and name CA and resid 27:57 or resid 63:91 or resid 100:134 or resid 145:170 or resid 186:218 or resid 322:354 or resid 362:400')
    segR_I = segR_CA.moment_of_inertia()
    # principal_axes
    segR_UT = segR_CA.principal_axes()

    # atomselection
    segA_CA = u.select_atoms('protein and segid C'+ga_chainid+' and name CA')
    segA_I = segA_CA.moment_of_inertia()
    # principal_axes
    segA_UT = segA_CA.principal_axes()

    Va=segR_UT[0]+segR_UT[1]+segR_UT[2]
    Vb=segA_UT[0]+segA_UT[1]+segA_UT[2]
    rotM = rot(Va,Vb)
    rotM2=R.from_matrix(rotM)
    rotM2.as_euler('zyx', degrees=True)
    print(rotM2.as_euler('xyx', degrees=True))
    


[ 158.94346495   33.27680148 -108.95129557]
[ 159.86645114   33.2083446  -109.98162423]
[ 159.8189848    34.04869059 -108.50541297]
[ 161.31080026   33.49216152 -110.95358901]
[ 160.26163783   33.75764982 -109.44089462]
[ 160.3906015    33.62794588 -109.79133645]
[ 159.26290974   33.22235632 -109.35809795]
[ 159.34852159   33.91408413 -108.27166952]
[ 161.05277126   33.47359965 -110.72313678]
[ 159.22042322   33.10956442 -109.50649079]
[ 158.52975222   33.02290193 -108.97204942]
[ 158.62617137   33.06326917 -108.99885474]
[ 158.72459021   33.68471466 -108.0498175 ]
[ 159.93806757   33.84291434 -108.9737391 ]
[ 161.07920998   33.85995232 -110.08607878]
[ 160.89381484   33.50894633 -110.50147253]
[ 160.10710307   32.89565446 -110.75377897]
[ 160.84925129   33.31483585 -110.78886751]
[ 160.7354348    33.23242596 -110.81453579]
[ 159.11648252   33.18939678 -109.26907071]
[ 159.58555769   33.24460414 -109.64030628]
[ 158.59363616   32.89671624 -109.24638318]
[ 159.96234047   33.20477385 -11

[ 159.45717121   34.1346214  -108.00373192]
[ 160.84053583   34.0381231  -109.53951459]
[ 159.45547147   34.35654473 -107.62478   ]
[ 159.95479833   34.04063871 -108.65321827]
[ 159.83763006   33.40346361 -109.62157814]
[ 161.06944366   34.10846308 -109.6484593 ]
[ 159.84036683   34.0402296  -108.54091903]
[ 159.45798755   34.01465514 -108.20832457]
[ 161.06235002   34.86102895 -108.34245031]
[ 161.12775123   34.44834706 -109.12086969]
[ 160.73925784   34.57560851 -108.51376783]
[ 160.44095527   34.45584263 -108.42375779]
[ 159.80320462   33.88895969 -108.76186768]
[ 160.47255423   34.1036405  -109.05922928]
[ 161.18704212   34.48653298 -109.11434615]
[ 161.8618472    33.83373987 -110.92692545]
[ 160.41231473   33.90862894 -109.3331334 ]
[ 159.98477943   34.12186593 -108.54424155]
[ 160.05213826   33.60600335 -109.49068843]
[ 160.40323634   33.99068843 -109.18363411]
[ 160.83309325   34.5662298  -108.6232429 ]
[ 159.67618334   34.40819841 -107.75244885]
[ 160.33765844   34.39638431 -10

[ 158.96571723   33.73375978 -108.20224074]
[ 158.5970474    33.54636646 -108.15854708]
[ 158.37769265   33.6126877  -107.83398184]
[ 159.29197445   33.72593268 -108.5350431 ]
[ 157.94019724   33.2017134  -108.09841705]
[ 158.17193917   33.24951483 -108.24324257]
[ 158.05728009   33.42229287 -107.84295802]
[ 158.51916927   33.80035491 -107.6555811 ]
[ 157.93224137   33.76521139 -107.14854667]
[ 158.27520162   33.95370216 -107.16212067]
[ 160.3902564    34.31012155 -108.62349497]
[ 160.03339767   34.45860997 -108.01677754]
[ 160.0104646    34.10399133 -108.60013169]
[ 158.7127554    33.99827478 -107.50963693]
[ 159.26903635   33.65710523 -108.62903865]
[ 159.00107183   33.01045862 -109.45667005]
[ 158.86020651   33.52585182 -108.44991073]
[ 159.69303347   33.65064571 -109.05816337]
[ 159.70240681   33.48183659 -109.35409676]
[ 159.4689568    33.68154101 -108.78440662]
[ 160.5477508    33.69586649 -109.83272181]
[ 160.71726692   34.23955552 -109.06998108]
[ 160.10887379   34.25867126 -10

[ 162.19959055   34.73315926 -109.70828809]
[ 160.90751307   35.0085708  -107.93369681]
[ 162.9185685    34.87273046 -110.19862898]
[ 161.49944182   34.51655616 -109.37637201]
[ 161.86131071   34.42185794 -109.90662226]
[ 162.96303662   34.82783894 -110.32322569]
[ 162.93338922   34.45699305 -110.94345938]
[ 164.61396657   34.86579248 -111.97899821]
[ 164.38337678   34.56595174 -112.26791545]
[ 161.92697336   34.71907553 -109.45633142]
[ 163.4297063    34.50069125 -111.38174361]
[ 162.71810048   34.90484604 -109.93670158]
[ 162.61720283   34.67977912 -110.22781944]
[ 161.99737816   34.21964791 -110.39632559]
[ 162.85626739   34.37097217 -111.01442941]
[ 162.44291463   34.44862201 -110.45327932]
[ 161.33361676   34.3825454  -109.44132127]
[ 160.96114994   34.08803832 -109.57475715]
[ 160.97620078   34.56958399 -108.76007327]
[ 160.47667704   34.68029514 -108.0735351 ]
[ 162.08818381   34.5751154  -109.87055774]
[ 161.66797148   34.11795864 -110.23722489]
[ 162.92279386   34.89203281 -11

[ 162.15742665   34.76064425 -109.61749153]
[ 160.8727746    34.29700089 -109.12654175]
[ 160.96173128   33.89032759 -109.9153649 ]
[ 160.82833533   34.10994954 -109.40382866]
[ 161.80337211   33.93557023 -110.69087994]
[ 160.97812208   34.1523353  -109.48113516]
[ 161.54329698   34.29640044 -109.8019271 ]
[ 162.4177929    34.50215277 -110.33409802]
[ 161.89629923   34.35881305 -110.05166893]
[ 161.64997583   34.0282002  -110.3742586 ]
[ 161.1181086    34.05323162 -109.79259773]
[ 161.51718176   34.30641759 -109.75818116]
[ 160.9765735    33.81166652 -110.06551252]
[ 160.2798362    33.90838497 -109.20149855]
[ 162.13629293   34.15471999 -110.65111585]
[ 161.6844793    34.13622554 -110.22237377]
[ 158.88746452   33.18099957 -109.05758499]
[ 159.32029391   34.21701522 -107.73003402]
[ 161.50805975   34.25566682 -109.83678265]
[ 161.2027941    34.4608045  -109.17459686]
[ 162.57411113   34.66423396 -110.21088044]
[ 161.20183226   34.34337171 -109.37646142]
[ 162.02458763   34.69264253 -10

[ 162.48423542   33.87560811 -111.49442935]
[ 162.21158341   33.86722184 -111.22780129]
[ 161.02890974   34.19525458 -109.45821212]
[ 162.88402925   34.54291252 -110.74189851]
[ 161.48052998   34.67061944 -109.0903107 ]
[ 162.97983011   34.2546613  -111.34598927]
[ 163.26514873   34.57886638 -111.07308723]
[ 163.43597752   34.7407909  -110.96531668]
[ 163.1397992    34.66144519 -110.79801635]
[ 163.30745303   34.77900519 -110.76466968]
[ 165.33986481   35.25598203 -112.05248669]
[ 165.12488422   35.27124509 -111.79617294]
[ 164.00287276   34.98991941 -111.11544026]
[ 163.66737976   34.94298621 -110.84875865]
[ 163.17162528   34.93308263 -110.3528958 ]
[ 162.02283869   34.83608187 -109.34949016]
[ 163.56986728   34.71701466 -111.14649885]
[ 164.39691445   35.02821569 -111.460679  ]
[ 163.35841469   35.43332418 -109.66186953]
[ 164.56812459   35.26922031 -111.21111922]
[ 164.48377981   35.03036587 -111.54832583]
[ 164.48668307   35.2015209  -111.24628499]
[ 163.67107765   34.98596445 -11

[ 159.94671884   33.50534429 -109.55702508]
[ 157.33817957   33.35412807 -107.26491657]
[ 160.34402435   33.49419616 -109.97303223]
[ 161.25408981   34.07541127 -109.89152543]
[ 161.37213331   34.14778983 -109.88584238]
[ 160.76450449   34.05347446 -109.43692313]
[ 159.70889201   33.68108984 -109.02213554]
[ 160.30510631   33.73067813 -109.53034491]
[ 160.94659943   34.19375391 -109.37820394]
[ 161.41169296   33.99568691 -110.18851866]
[ 160.71167483   33.81657048 -109.79049132]
[ 160.09172812   33.43630947 -109.81916656]
[ 159.85921137   33.69721732 -109.14363135]
[ 159.12549456   33.59740295 -108.5890507 ]
[ 160.95491974   34.12413403 -109.50638518]
[ 160.33562492   33.59246839 -109.79687773]
[ 159.82081544   33.62065439 -109.23576396]
[ 160.08537617   34.06409103 -108.74237115]
[ 160.5827763    33.91118623 -109.49909305]
[ 159.32590372   33.51754722 -108.92121285]
[ 159.32204589   33.55073611 -108.86124056]
[ 159.15096216   33.13143002 -109.40089983]
[ 160.57782513   34.03659863 -10

[ 158.12087298   33.13487288 -108.38542196]
[ 157.36032695   32.58850191 -108.55727953]
[ 158.27746399   33.32438275 -108.22037501]
[ 157.66550575   33.16935327 -107.88691098]
[ 158.78946321   33.23055847 -108.87790781]
[ 159.09958149   33.5947544  -108.56810176]
[ 158.01722954   33.55750765 -107.5779885 ]
[ 160.21419195   33.58662402 -109.6854015 ]
[ 158.82453335   33.73677983 -108.05939493]
[ 160.64602694   34.00873859 -109.39511554]
[ 158.93413715   33.82796618 -108.01230744]
[ 158.83543261   33.39696953 -108.64283616]
[ 159.43508725   33.51618089 -109.03124584]
[ 157.03558863   33.56903902 -106.61958416]
[ 159.35668765   33.50357558 -108.97521449]
[ 158.61870923   33.60157871 -108.08674088]
[ 159.0488065    33.57498692 -108.55169937]
[ 158.03598819   33.40195922 -107.85639055]
[ 158.6478402    33.15698722 -108.8627136 ]
[ 157.87796867   33.45790693 -107.61030384]
[ 159.2702727    33.64582259 -108.64935109]
[ 159.18202233   33.55202919 -108.72126522]
[ 158.65652009   33.2922407  -10

[ 155.82060015   32.75926062 -106.80477453]
[ 156.53341657   32.70958034 -107.56245082]
[ 157.48076946   33.24540849 -107.58245006]
[ 157.61749096   33.01815619 -108.09232578]
[ 157.39128679   33.55761979 -106.97716615]
[ 158.04195991   33.63813238 -107.46684607]
[ 158.17233818   33.06819477 -108.54700902]
[ 159.23795392   33.6187652  -108.66337245]
[ 159.9421481    33.21042662 -110.05373831]
[ 158.28038186   33.4182982  -108.06578492]
[ 159.2655679    33.7810816  -108.41572504]
[ 157.89404353   33.8849011  -106.91155479]
[ 158.21526099   33.19096523 -108.38335998]
[ 157.29415485   33.144773   -107.57057617]
[ 157.41360356   33.95512773 -106.3361691 ]
[ 158.27891784   33.47724188 -107.96552832]
[ 158.9757309    33.30328525 -108.93838187]
[ 158.39652501   34.1894021  -106.88235096]
[ 157.48209058   33.04371907 -107.919168  ]
[ 158.09321431   33.08609508 -108.44008189]
[ 157.04117884   33.23646787 -107.17643575]
[ 158.44544148   33.25758498 -108.4959336 ]
[ 157.38537468   32.89753453 -10

[ 157.83111368   32.48799252 -109.18200274]
[ 158.01839518   32.63628463 -109.11803492]
[ 158.50186346   33.17156989 -108.69535029]
[ 159.91102986   33.07501419 -110.25247186]
[ 158.40609161   33.09500093 -108.73015348]
[ 159.20121372   33.58038233 -108.69218749]
[ 158.89363212   33.06439616 -109.25990337]
[ 157.84138002   32.59229985 -109.01845536]
[ 158.09664383   33.01722532 -108.55852027]
[ 158.4945057    33.18534283 -108.66504879]
[ 158.05650563   33.24302808 -108.14207448]
[ 159.23327238   33.5557114  -108.76543226]
[ 157.65653341   32.87548213 -108.36751347]
[ 158.75866815   32.9234874  -109.36383158]
[ 159.48309885   33.21330464 -109.5915389 ]
[ 158.85979698   33.35024223 -108.74542311]
[ 158.88481507   33.26113036 -108.92006101]
[ 159.42935325   33.04448007 -109.82363182]
[ 159.20184545   33.06844172 -109.55748425]
[ 158.39809321   33.32343889 -108.33930605]
[ 158.86307232   32.8318761  -109.62073144]
[ 158.88990668   33.44389493 -108.61713615]
[ 160.3151404    33.69528896 -10

[ 155.44887498   32.15309223 -107.44331941]
[ 156.49776815   32.15697517 -108.43731707]
[ 156.14198727   32.76921182 -107.09223498]
[ 156.20537162   32.53784017 -107.53220176]
[ 158.87870089   32.93122982 -109.46916449]
[ 157.19160538   32.55470297 -108.45008847]
[ 157.3637978    32.46703465 -108.76195856]
[ 155.99131913   32.58888875 -107.24518779]
[ 156.73217375   32.67698056 -107.80615616]
[ 156.37894638   32.73200785 -107.37835897]
[ 156.4962895    32.70162754 -107.54013072]
[ 157.0831715    32.77793968 -107.97609817]
[ 155.82419712   32.70052445 -106.9043073 ]
[ 157.21116137   32.6049088  -108.38586312]
[ 157.84236839   32.90965597 -108.49083257]
[ 156.62722582   32.76916071 -107.55380843]
[ 157.08608587   33.13874381 -107.38129991]
[ 158.41001761   32.91266745 -109.03946822]
[ 158.51738841   33.07084557 -108.87952143]
[ 157.44733401   32.57617251 -108.66202846]
[ 156.82146972   32.83649695 -107.62831539]
[ 157.86889441   32.69394921 -108.87603328]
[ 156.9253169    33.11471732 -10

[ 156.51643869   33.70320516 -105.90723227]
[ 158.61345258   33.466957   -108.30809286]
[ 158.49803901   33.8743157  -107.51065405]
[ 160.12247594   33.6045531  -109.56327389]
[ 159.88844903   33.6185315  -109.30652211]
[ 159.48219294   33.17846012 -109.64959275]
[ 158.03605253   33.14663359 -108.28336853]
[ 157.93031358   32.83257173 -108.70483997]
[ 157.18366419   32.91326591 -107.84855062]
[ 158.34532329   33.01857346 -108.7988101 ]
[ 158.02035307   33.02750458 -108.46713606]
[ 157.74447449   33.40577709 -107.56879254]
[ 158.56061346   33.53936451 -108.13485689]
[ 157.79916899   33.4474513  -107.55187138]
[ 157.9771519    34.15645177 -106.5359942 ]
[ 157.12465332   33.39536375 -106.99250668]
[ 159.09462918   32.98521935 -109.59166658]
[ 157.99977403   32.31347142 -109.63756824]
[ 157.36290223   33.26218051 -107.44144542]
[ 158.24255519   32.83099643 -109.01217451]
[ 157.7173215    32.92041205 -108.35162143]
[ 157.71334748   33.12230954 -108.0114764 ]
[ 157.51795645   33.56981037 -10

[ 156.74801177   32.72240988 -107.7463711 ]
[ 157.49358348   32.75274946 -108.41375109]
[ 156.69882672   32.5987842  -107.90316299]
[ 157.13911332   32.63765436 -108.26213527]
[ 157.64740921   33.16555663 -107.87578163]
[ 157.06062325   32.5262284  -108.37074984]
[ 156.92755293   31.9795196  -109.14434381]
[ 157.2226558    32.85926507 -107.97555237]
[ 158.46431863   33.89135679 -107.44937113]
[ 158.93926867   33.14764298 -109.16472835]
[ 157.9879238    33.06794542 -108.36809381]
[ 158.05232266   33.10575103 -108.36748706]
[ 158.3383047    33.16789462 -108.54183256]
[ 157.93519796   33.26570851 -107.98668427]
[ 158.40620385   33.30976068 -108.37015167]
[ 158.67328708   33.21091877 -108.79702802]
[ 160.043237     33.59130132 -109.50686194]
[ 158.48870387   33.51129635 -108.11208042]
[ 158.7640581    33.11786471 -109.04249721]
[ 159.59181348   33.29228127 -109.56575686]
[ 158.8514037    33.52044973 -108.45040672]
[ 158.87573857   33.39830083 -108.6800893 ]
[ 157.37503822   33.04131211 -10

[ 157.68987413   32.71295373 -108.67022692]
[ 158.12903809   33.06523363 -108.50980575]
[ 157.56495173   33.31009163 -107.55566115]
[ 157.95542387   33.05807688 -108.35301857]
[ 159.56329503   33.4796699  -109.21988771]
[ 157.4504196    32.88814497 -108.14715218]
[ 157.28442347   32.64323926 -108.39314189]
[ 158.14984507   32.97245863 -108.68516371]
[ 158.81640908   32.20448694 -110.62689331]
[ 158.43871976   32.50929754 -109.74265902]
[ 158.2567904    32.50481737 -109.57105964]
[ 158.79928398   32.0752535  -110.82616601]
[ 158.65603265   32.9008842  -109.30074475]
[ 159.61298104   32.24427762 -111.35790676]
[ 158.96433728   32.78569986 -109.79850374]
[ 157.67097551   32.77295593 -108.55207831]
[ 159.46441608   32.53695587 -110.71529611]
[ 157.68915545   32.65902253 -108.75921651]
[ 158.0441333    32.48400101 -109.39705779]
[ 158.45145949   32.67238129 -109.48240961]
[ 158.64741915   33.29886892 -108.62387938]
[ 159.70458381   32.9492262  -110.25910432]
[ 159.53576797   33.7469074  -10

[ 159.2041305    33.6924691  -108.50545279]
[ 160.0382525    33.67326314 -109.36227949]
[ 160.17012111   33.92319733 -109.06706011]
[ 159.94578291   33.07971543 -110.27930142]
[ 159.03941781   33.45550613 -108.74420664]
[ 158.37598179   33.50553037 -108.01224008]
[ 159.56831082   33.74397084 -108.77644693]
[ 158.40081597   33.83753294 -107.47853375]
[ 157.31470621   33.64964186 -106.75099746]
[ 159.56523125   33.49874784 -109.18945787]
[ 159.34634799   33.64034834 -108.73344913]
[ 159.19292505   33.88643892 -108.16614338]
[ 156.99275903   33.42562565 -106.81676795]
[ 158.64648574   33.08343866 -108.98491749]
[ 158.13684205   33.25869682 -108.19379831]
[ 159.14956151   33.27929497 -109.15001982]
[ 160.15302697   33.67061459 -109.48111179]
[ 159.9510023    33.68801617 -109.25040414]
[ 159.27733802   33.83718022 -108.3322413 ]
[ 159.10883943   33.67970965 -108.43359345]
[ 159.60386282   33.28472289 -109.59053163]
[ 158.53097549   33.34349083 -108.43516047]
[ 159.5951573    33.57752765 -10

[ 158.33476976   33.52777943 -107.93490951]
[ 158.11427492   32.96958653 -108.65529654]
[ 157.73394202   33.06496163 -108.12694231]
[ 156.8962422    33.04786492 -107.35039095]
[ 158.79458889   32.84672434 -109.52817337]
[ 157.65307625   32.58259788 -108.85117219]
[ 159.11392427   33.35830357 -108.981537  ]
[ 158.70403889   33.1963367  -108.85167531]
[ 158.00705884   33.28983744 -108.0159055 ]
[ 157.11002035   32.9140157  -107.77658281]
[ 158.95837854   32.97904496 -109.46738621]
[ 158.54582315   33.6187116  -107.98703418]
[ 158.37429607   33.22572903 -108.47998672]
[ 158.79197809   33.50923748 -108.4112009 ]
[ 158.00740291   33.31106682 -107.98074695]
[ 158.8971397    33.69729897 -108.19682687]
[ 157.64531543   32.89300931 -108.32748706]
[ 158.4638225    33.44447054 -108.20013432]
[ 159.27818862   33.63111556 -108.68202644]
[ 158.50104678   33.41669267 -108.28302911]
[ 159.44294397   33.17817089 -109.61112058]
[ 159.20747115   33.37182094 -109.05087379]
[ 160.61038287   33.7090782  -10

[ 161.60906719   34.52826026 -109.46662535]
[ 161.59386179   34.44387578 -109.59758111]
[ 161.22764641   34.44107663 -109.23362502]
[ 161.33587018   33.78129974 -110.48135153]
[ 160.7858496    33.84499239 -109.81625561]
[ 160.37648727   34.09713202 -108.97476172]
[ 161.65691852   33.9453917  -110.52454692]
[ 161.32709019   33.99794294 -110.09894476]
[ 160.89539993   33.75734645 -110.07695177]
[ 161.86909247   33.91202933 -110.79879127]
[ 160.91835371   33.67680625 -110.23835105]
[ 161.2967148    33.43851058 -111.031486  ]
[ 161.60777324   34.31939912 -109.82734028]
[ 159.83700566   33.9139061  -108.7527959 ]
[ 160.84509956   34.64074528 -108.50674348]
[ 160.99656713   34.46827551 -108.9551834 ]
[ 162.22770787   34.65039721 -109.88130198]
[ 161.35496975   34.27816231 -109.64326927]
[ 162.18448421   34.55597685 -110.00192728]
[ 161.7256933    34.27937727 -110.01621112]
[ 162.31210826   34.47673458 -110.27033458]
[ 161.52432666   34.00597045 -110.28501018]
[ 162.80676294   34.14648909 -11

[ 161.99371097   33.75804691 -111.1931554 ]
[ 160.94442059   33.85379444 -109.96070997]
[ 160.6938099    33.65311371 -110.05265658]
[ 159.98472711   33.71334215 -109.2407793 ]
[ 159.70714022   33.0006405  -110.17461088]
[ 160.44903969   33.03037556 -110.86960262]
[ 159.8644615    33.65466413 -109.22123617]
[ 159.88173183   33.40894678 -109.65618376]
[ 160.26742039   33.76263947 -109.43814182]
[ 161.23183174   33.64277797 -110.61420892]
[ 160.77641437   33.60372402 -110.22047147]
[ 160.80344983   34.00132015 -109.56554313]
[ 161.20022059   33.81209038 -110.29079649]
[ 161.11937027   33.95535231 -109.96243609]
[ 162.06863121   34.42035794 -110.12006799]
[ 161.21999539   33.77514943 -110.37441713]
[ 161.06513523   33.16310875 -111.26809511]
[ 160.43158536   33.70492716 -109.7008121 ]
[ 161.51071987   33.57518691 -111.01454641]
[ 160.87124246   33.76214849 -110.04436169]
[ 161.49460174   33.61940855 -110.92188066]
[ 162.85801209   33.89598957 -111.8464555 ]
[ 162.11509096   34.04815057 -11

[ 160.97333596   33.32603842 -110.89555234]
[ 161.87801339   33.18468859 -112.06482413]
[ 161.08347926   33.57408981 -110.58175985]
[ 162.54103606   33.54633951 -112.12570881]
[ 161.71986236   34.10751449 -110.30806371]
[ 160.19189773   33.36376932 -110.04291949]
[ 160.9448521    33.4833613  -110.59699396]
[ 159.9686368    32.90447832 -110.5995436 ]
[ 159.37761192   32.58034521 -110.55531501]
[ 159.82010633   32.4585127  -111.205096  ]
[ 159.00073422   32.1555248  -110.89278556]
[ 158.82421403   32.4935684  -110.15018772]
[ 161.53073526   33.25387851 -111.5882815 ]
[ 160.42943803   33.22715452 -110.51442368]
[ 160.74013729   32.82251836 -111.5192239 ]
[ 159.11733632   32.67648008 -110.13399978]
[ 160.94611687   33.12433483 -111.21328162]
[ 162.3679233    33.32047975 -112.33759144]
[ 161.39143342   33.36897502 -111.24770589]
[ 161.78073769   33.3049909  -111.75711867]
[ 160.98841772   33.77316798 -110.1436131 ]
[ 162.65371643   33.86675509 -111.68529421]
[ 162.09211097   33.52138001 -11

[ 162.42818164   34.33145837 -110.64259944]
[ 161.06334985   34.4001789  -109.13947578]
[ 162.25557484   34.43592539 -110.2837008 ]
[ 162.71303819   34.41234641 -110.79424514]
[ 161.97998344   34.01469391 -110.73427509]
[ 161.17515345   34.22457747 -109.55465832]
[ 162.13048191   34.15923421 -110.63732131]
[ 162.43912841   34.25529335 -110.7866554 ]
[ 162.90982169   34.15625258 -111.44557889]
[ 162.4321618    34.20467459 -110.86772787]
[ 161.02475758   34.00400481 -109.78332811]
[ 162.37334806   34.35939476 -110.53764034]
[ 161.16642374   33.87465719 -110.14889201]
[ 161.70114322   33.76452932 -110.8822904 ]
[ 162.1616384    34.29444005 -110.43406955]
[ 162.89005953   34.56316305 -110.71261781]
[ 162.92239828   34.47569819 -110.89931849]
[ 161.01925405   34.45495736 -109.00084034]
[ 161.98971704   34.26331234 -110.3126666 ]
[ 163.01123805   34.56080647 -110.84185402]
[ 161.58198503   33.90802774 -110.51284708]
[ 162.51569585   34.48524135 -110.46395707]
[ 162.67447716   33.96458195 -11

[ 163.73039787   34.48150555 -111.72969819]
[ 164.76445833   34.72959198 -112.38129268]
[ 162.27302023   34.34129635 -110.46642169]
[ 162.11565586   34.07955441 -110.76058522]
[ 163.33344593   34.53262725 -111.22536175]
[ 163.34863767   34.6449968  -111.04338816]
[ 163.15196244   34.87461661 -110.43557382]
[ 162.62698172   34.58935927 -110.39609629]
[ 162.43127477   34.32517426 -110.65673439]
[ 162.12306514   34.36871464 -110.26543201]
[ 163.6312782    34.53116395 -111.53840069]
[ 162.43850611   34.56212725 -110.25056704]
[ 165.21637355   35.33611075 -111.7770084 ]
[ 163.97189583   35.1830256  -110.74033332]
[ 164.51863556   35.24618064 -111.20020011]
[ 164.10880101   34.93436265 -111.32491772]
[ 163.89683425   35.01310237 -110.96358762]
[ 162.34327416   34.66252048 -109.97792454]
[ 162.67749513   34.41049918 -110.76086756]
[ 163.20096721   34.35940503 -111.3920066 ]
[ 162.78679148   34.19925772 -111.24294117]
[ 163.31552693   34.57714289 -111.12842528]
[ 163.47211424   34.91754756 -11

[ 163.66869878   35.41710912 -110.01020691]
[ 162.93743609   35.04543949 -109.91434123]
[ 164.90849735   35.66964634 -110.85225199]
[ 164.40093779   35.96708528 -109.78797068]
[ 163.68112853   35.59402001 -109.70893873]
[ 161.70705989   35.36406994 -108.11136405]
[ 163.07923741   35.19671381 -109.79331663]
[ 162.38680576   35.28713035 -108.92906343]
[ 164.01752792   35.65180435 -109.95371789]
[ 163.8892533    35.54694571 -110.00760007]
[ 163.34490575   35.63474962 -109.2913158 ]
[ 164.81312889   35.58545086 -110.90298233]
[ 166.65725473   35.83892658 -112.41452552]
[ 165.23516192   35.58413587 -111.35108215]
[ 163.75178915   35.26206509 -110.37125201]
[ 164.48651259   35.50505494 -110.704117  ]
[ 164.002729     35.23347677 -110.68283425]
[ 163.47136597   35.75078543 -109.21502229]
[ 164.26472402   35.52913561 -110.42938873]
[ 162.30679706   34.81878483 -109.66777532]
[ 163.10353104   35.01648216 -110.13587184]
[ 162.93308829   35.45786722 -109.18341185]
[ 162.58766045   34.89997485 -10

In [20]:
PDB="/home/khlee/desmond/output/drd3ao/pd2/drd3ao_pd2.f2/init_ref.protein.pdb"
DCDs=glob.glob('/home/khlee/desmond/output/drd3ao/pd2/drd3ao_pd2.f2/drd3ao_pd2.f2_e0-2400.protein.wrapped.dcd')
u = mda.Universe(PDB, DCDs)

In [21]:
for ts in u.trajectory:
    #print (ts)

    # atomselection
    segR_CA = u.select_atoms('protein and segid C'+rec_chainid+' and name CA and resid 27:57 or resid 63:91 or resid 100:134 or resid 145:170 or resid 186:218 or resid 322:354 or resid 362:400')
    segR_I = segR_CA.moment_of_inertia()
    # principal_axes
    segR_UT = segR_CA.principal_axes()

    # atomselection
    segA_CA = u.select_atoms('protein and segid C'+ga_chainid+' and name CA')
    segA_I = segA_CA.moment_of_inertia()
    # principal_axes
    segA_UT = segA_CA.principal_axes()

    Va=segR_UT[0]+segR_UT[1]+segR_UT[2]
    Vb=segA_UT[0]+segA_UT[1]+segA_UT[2]
    rotM = rot(Va,Vb)
    rotM2=R.from_matrix(rotM)
    rotM2.as_euler('zyx', degrees=True)
    print(rotM2.as_euler('xyx', degrees=True))
    


[148.92847105  33.7659691  -99.09008445]
[148.74689098  33.65199344 -99.11320282]
[149.34793079  33.74215705 -99.47788487]
[149.52848034  33.6935274  -99.70480837]
[149.60336359  34.04646065 -99.22291881]
[148.8412003   33.54070515 -99.36241135]
[148.83809575  33.86771773 -98.85884311]
[148.56821367  33.6640951  -98.94588394]
[147.81253445  33.47206243 -98.61190445]
[149.51538172  33.77576546 -99.56688118]
[150.52078061  34.23479181 -99.70373497]
[150.87782736  34.49598753 -99.59809381]
[150.2302268   33.96957926 -99.87049098]
[151.01229427  34.8382706  -99.17543017]
[150.17442014  34.30595565 -99.30053727]
[150.10277388  34.04280134 -99.64888152]
[149.84181495  33.70087356 -99.95824296]
[ 151.3450736    34.20143732 -100.45886795]
[ 151.64485402   34.043841   -100.9654327 ]
[149.82475188  34.49764212 -98.71031924]
[150.12112023  34.45358101 -99.02642553]
[149.88576363  34.46063321 -98.81855234]
[152.62382499  35.24803369 -99.89842457]
[ 152.39569333   34.92964167 -100.20975395]
[ 151.6

[148.89056362  33.30179795 -99.76993001]
[ 150.13596377   33.11922554 -101.11097117]
[ 149.72646919   33.56063189 -100.07747437]
[ 149.09731706   32.67187914 -100.91163337]
[ 150.89957438   33.03143363 -101.90868834]
[ 150.86300133   32.71211108 -102.37599679]
[ 151.41327451   33.01501965 -102.38370622]
[ 149.82045341   32.80556923 -101.32555305]
[ 151.03585452   32.64657358 -102.6301335 ]
[ 148.56992085   32.47507699 -100.7636162 ]
[ 150.34296467   32.18203706 -102.74643946]
[ 150.23004305   32.25022731 -102.54162686]
[ 149.08802828   32.64104314 -100.95105211]
[ 148.49549568   32.38520639 -100.83752182]
[ 149.78676174   32.5116655  -101.75102781]
[ 148.9861584    33.05944717 -100.22223856]
[ 149.43287834   32.5589977  -101.37279502]
[ 150.10407615   32.75649921 -101.6463395 ]
[ 150.07758281   32.72910276 -101.66591158]
[ 149.85599741   32.4047943  -101.97629037]
[ 148.52931832   32.87265129 -100.12204996]
[ 149.77942529   32.77904243 -101.33126471]
[148.68711105  33.06090613 -99.9674

[ 148.26603916   32.01890329 -101.20035391]
[ 148.2818257    32.07517183 -101.12814238]
[ 149.23855233   32.85253764 -100.75451479]
[ 150.05421406   32.91212095 -101.36190113]
[ 148.72254112   32.22903577 -101.26993583]
[ 148.19460206   32.64181792 -100.19155363]
[ 148.75379111   32.40583988 -101.02614851]
[ 147.49614971   31.70553244 -101.02007227]
[146.00448331  32.58844362 -98.45241069]
[ 148.00601767   32.57055379 -100.14096002]
[ 148.37697979   32.27452783 -100.90547824]
[ 149.45036016   32.01523314 -102.2256638 ]
[ 149.94941035   32.21017404 -102.35872666]
[ 148.24373317   32.55833883 -100.3600922 ]
[148.56522447  33.09177134 -99.81764857]
[146.64718306  32.28028032 -99.44228738]
[ 148.08091742   32.64520472 -100.09061057]
[ 147.90440959   32.38084837 -100.34326292]
[ 148.69587987   32.95966767 -100.12966687]
[ 149.15239109   32.49034732 -101.23759993]
[ 150.0717994    32.8599221  -101.45802346]
[ 149.11468588   33.09389631 -100.27821467]
[ 148.5395405    32.63508252 -100.4934559

[ 149.68294162   33.45750377 -100.19996274]
[ 149.79467377   33.4095715  -100.36904655]
[149.67111856  33.84886638 -99.58513811]
[ 149.19529427   33.21419533 -100.16161334]
[148.93898464  33.29604139 -99.81951599]
[148.76825653  33.49447912 -99.37215195]
[ 149.82173961   33.42975146 -100.36085535]
[148.74887123  33.48479335 -99.37075546]
[ 149.17359855   33.2202025  -100.1340142 ]
[149.89321674  33.77831359 -99.88184437]
[ 150.37908205   33.72384893 -100.37937848]
[ 150.47946688   33.80631133 -100.33661168]
[ 149.47802155   32.94369296 -100.81855927]
[ 150.44119004   32.97684849 -101.59571498]
[ 149.81029729   32.51698299 -101.76316447]
[ 149.80689086   32.45700655 -101.85296807]
[ 148.2791241    32.00417515 -101.23395515]
[ 149.13834932   32.51046491 -101.19465723]
[ 148.71261473   32.52381762 -100.81054004]
[ 149.24043979   31.58774148 -102.70079907]
[ 150.41873803   31.85364813 -103.3235807 ]
[ 149.39346339   32.33890466 -101.67787859]
[ 149.82041237   32.24444552 -102.19340521]
[ 1

[148.80741263  33.39375229 -99.55918563]
[148.80158552  34.13938441 -98.41245954]
[ 150.35592963   33.52335433 -100.67164534]
[148.83333273  33.70914349 -99.09780031]
[148.28252562  33.51749305 -98.9320604 ]
[147.93071078  33.278819   -99.00277889]
[147.66190694  33.12022297 -99.0200627 ]
[ 149.37918213   32.81736653 -100.9287411 ]
[ 149.25121812   32.77820388 -100.87965549]
[ 149.13863119   32.76024099 -100.8111663 ]
[147.7210414   33.07749313 -99.1338285 ]
[147.80723395  32.63286514 -99.87934757]
[147.14776792  33.03812348 -98.71877718]
[ 148.56289793   32.41727766 -100.84592219]
[ 148.9205085    32.92067316 -100.37944793]
[148.32326338  33.18597398 -99.47103474]
[ 149.50821097   33.48020174 -100.01681704]
[ 149.22734257   32.90962021 -100.65717174]
[148.58305971  33.36099349 -99.42132301]
[ 149.93938409   33.42931953 -100.46173559]
[148.32461357  33.04048353 -99.69385001]
[148.07762404  33.41553464 -98.91708665]
[148.50764035  33.45808436 -99.21003113]
[ 148.9506081    33.01912683 -

[ 150.55111411   33.60189062 -100.71658286]
[149.48564097  33.62078814 -99.78089094]
[ 151.19471397   33.0954678  -102.06591204]
[ 149.80491115   33.03374212 -100.95922178]
[ 150.02672671   32.59892542 -101.82370174]
[ 149.22696203   33.2864089  -100.07736286]
[148.5173439   33.07033557 -99.81013303]
[ 149.20919826   33.32179214 -100.00792727]
[148.79486375  33.64541227 -99.16330708]
[148.3241293   33.41023396 -99.13005369]
[148.76918209  33.32918937 -99.62595392]
[ 149.3109051    32.86172543 -100.80211098]
[148.87540622  33.35454871 -99.67633738]
[ 148.76809629   32.97364775 -100.16928353]
[146.0616201   33.06010737 -97.79735187]
[146.87885826  32.57644889 -99.19042035]
[146.07925957  33.04309986 -97.83697688]
[ 148.15070096   32.55252996 -100.29034693]
[148.05550913  32.79380504 -99.8434263 ]
[146.45243566  32.68417218 -98.67711681]
[ 147.8949628    32.4485377  -100.23260619]
[147.21468647  32.98914648 -98.84775014]
[ 148.712701     32.7432222  -100.47498824]
[147.94523333  32.749470

[148.34469443  33.95715635 -98.31368103]
[148.91497499  33.84990035 -98.95013872]
[149.22557802  33.77117242 -99.33055852]
[147.42828551  33.82260061 -97.76654714]
[147.11468356  33.61848537 -97.81844996]
[147.83120168  33.70167346 -98.27929248]
[148.08639299  33.37266163 -98.98952473]
[146.43041074  33.56837089 -97.33843317]
[146.76940123  33.20333749 -98.1599732 ]
[145.78345289  33.09614473 -97.51858855]
[146.98036241  33.4341089  -97.98603524]
[146.78563926  32.97041818 -98.52245544]
[146.96007006  33.25596558 -98.23701457]
[148.31713744  32.86393403 -99.95657033]
[147.16886125  32.52073044 -99.51513663]
[147.11583952  32.63729262 -99.29557967]
[145.37620022  32.65660087 -97.83976657]
[146.1867189   32.4249095  -98.84546593]
[146.71581004  32.55794154 -99.08319014]
[147.47320193  32.63689818 -99.59373208]
[146.87991717  32.87809424 -98.73851628]
[ 148.27093851   32.6490834  -100.24490133]
[ 147.70095662   32.27242632 -100.33597181]
[ 148.6825567    32.73742938 -100.45828872]
[145.38

[147.43073023  32.87212948 -99.20316251]
[147.47960403  33.08359705 -98.9243768 ]
[148.49267407  33.18942888 -99.60761965]
[146.88958989  33.25572968 -98.17968199]
[148.01737886  32.8565624  -99.71611197]
[146.39277256  33.04119438 -98.09497816]
[146.4512996   32.68082579 -98.6811835 ]
[146.48374682  32.86248822 -98.43632414]
[146.55548946  32.93818647 -98.38192761]
[145.89000689  32.67379053 -98.23201153]
[146.12441411  32.54765607 -98.61139048]
[145.94070952  32.25709695 -98.89281197]
[144.99127149  32.59265991 -97.62280816]
[146.49303783  32.83820702 -98.4802357 ]
[146.77070208  32.99915687 -98.46710482]
[147.08703303  32.4307625  -99.58236597]
[147.16019817  32.53871119 -99.48084979]
[ 147.0807426    32.04643726 -100.15532669]
[ 146.94644773   32.00556336 -100.10413246]
[147.28341533  32.53664404 -99.58664637]
[147.2039281   32.51741425 -99.54934904]
[147.64679854  32.62749206 -99.7530565 ]
[146.6736936   32.55528825 -99.05234037]
[147.93271133  33.07477601 -99.31407185]
[147.11083

[147.73818903  33.09759928 -99.117627  ]
[146.96691756  33.04817297 -98.55474711]
[148.05951618  32.91420069 -99.66384279]
[146.5507249   33.04227341 -98.22235163]
[147.40090245  33.5398443  -98.17081883]
[148.15573551  33.80467191 -98.3900737 ]
[147.61341002  33.09070502 -99.02449762]
[147.98488589  33.28033905 -99.04545924]
[147.35114618  33.29917195 -98.49300577]
[145.47511312  33.09194806 -97.27625208]
[146.61672998  32.67567769 -98.82504861]
[146.73208202  32.94021439 -98.52374096]
[147.01061465  33.50557895 -97.90334817]
[146.44113234  33.02328267 -98.16119579]
[146.65439625  33.00225736 -98.36708079]
[145.93520968  32.75017332 -98.15538191]
[145.06001026  33.10742649 -96.92054835]
[146.31134201  32.78300855 -98.41377429]
[145.45729833  32.57477167 -98.02651137]
[146.08429817  32.75681597 -98.26713862]
[146.47057514  32.43555725 -99.06364531]
[146.4308518   32.92684034 -98.29685872]
[146.07999042  33.14003037 -97.69334033]
[147.19139841  32.9852507  -98.83438003]
[146.39631256  3

[149.9378567   34.00996095 -99.56063256]
[147.99807067  33.71214045 -98.40074902]
[148.65080691  33.55028471 -99.18862484]
[148.11900166  33.63587094 -98.61643268]
[147.80799495  33.9483406  -97.88646123]
[148.56464711  34.53322414 -97.61533115]
[147.89913722  33.45417521 -98.710579  ]
[146.73653133  33.56588687 -97.58993996]
[147.31734535  33.73788767 -97.80385747]
[147.50232545  33.58351061 -98.18804688]
[146.8369228   34.04902066 -96.9470382 ]
[147.95237085  34.03722551 -97.86977339]
[147.84255846  33.76464609 -98.19317344]
[147.94926136  33.88916462 -98.09190673]
[149.02346868  33.72244292 -99.23622471]
[148.14457569  33.57835877 -98.72503999]
[146.84841389  33.6376363  -97.57317128]
[147.46977865  33.53937097 -98.2280091 ]
[148.03055771  34.14628338 -97.76814349]
[145.56212783  33.70313116 -96.44223391]
[147.401838    34.08275306 -97.35254793]
[146.37578418  33.92556305 -96.76142787]
[146.13782483  34.14152216 -96.24984373]
[147.3317901  34.1879057 -97.1373031]
[147.16597566  33.6

[147.57260439  33.08358249 -99.00143595]
[146.32392545  33.16465642 -97.85465807]
[147.084436    32.8432364  -98.95971241]
[147.04291573  33.13660323 -98.48433177]
[146.83176096  33.08131688 -98.39399942]
[146.78208319  33.77416505 -97.31477279]
[147.05278509  32.78444237 -99.02195426]
[145.28439229  32.87617636 -97.44139421]
[146.8843793   33.35254299 -98.0301368 ]
[145.65537636  32.79763594 -97.85742463]
[146.10232545  32.70468771 -98.35946946]
[147.31062067  32.85190804 -99.1339779 ]
[146.47675316  33.03786349 -98.16850002]
[147.6216058   32.87876205 -99.35188144]
[ 148.07098622   32.16580773 -100.81080203]
[146.30966882  31.85638546 -99.79532903]
[146.2262      32.61332073 -98.59705958]
[145.63754244  32.44739825 -98.36185648]
[146.26994312  32.66273384 -98.5592644 ]
[145.59449585  32.39343121 -98.40665478]
[144.77167615  32.20172788 -98.01987256]
[146.43558354  32.48066213 -98.96734382]
[147.28749451  32.4653233  -99.69756886]
[146.90306102  33.22380204 -98.23862689]
[146.00896356

[147.9244392   33.83485997 -98.15393069]
[147.71954741  33.82615166 -97.99914041]
[148.69154341  33.9916636  -98.54750092]
[148.27670804  34.00295111 -98.18793999]
[149.20928572  33.46920041 -99.78131302]
[147.96092356  34.12105037 -97.74955817]
[147.5647364   33.63790163 -98.15704408]
[148.62958392  33.82542805 -98.75033492]
[149.38371748  33.787403   -99.43824299]
[148.89457226  33.83511521 -98.95581085]
[147.42684196  33.86451277 -97.70212489]
[146.94951569  33.77170176 -97.45399051]
[149.25531455  33.82671279 -99.2700249 ]
[149.78586709  34.06546826 -99.34672431]
[148.5962521   33.92621034 -98.56868269]
[148.18676626  33.37096432 -99.075526  ]
[146.9682155  33.4728036 -97.9180067]
[145.92458836  32.97002795 -97.82006821]
[145.63330707  33.21854031 -97.21619396]
[147.97718767  33.25936374 -99.07090859]
[ 149.18270227   33.10370571 -100.32080864]
[147.95595004  33.58240903 -98.56294962]
[148.25323714  33.8118225  -98.45962039]
[148.44770833  33.66482437 -98.84463953]
[148.08889673  3

[149.23699588  33.57367031 -99.64396197]
[149.12107647  33.8822988  -99.07229254]
[149.31957985  33.65894776 -99.58219152]
[147.86056215  33.87972155 -98.03349595]
[148.67265252  33.68562106 -98.99989057]
[148.07226829  33.80636869 -98.31873163]
[148.27786084  33.70906158 -98.63644262]
[147.82859692  33.92547185 -97.93796954]
[148.04656558  34.07688373 -97.88664465]
[148.27114551  34.04594287 -98.11790055]
[147.09811015  34.00594775 -97.22233739]
[146.1536473   33.32676668 -97.47502532]
[148.14448566  33.71469181 -98.51763576]
[148.13176789  33.81197307 -98.35921807]
[147.39820368  33.6694131  -97.97312639]
[146.53811347  33.72195654 -97.19592306]
[147.89427873  33.71598629 -98.30946335]
[147.36768248  33.60345267 -98.04766397]
[147.87106121  33.9631015  -97.91567987]
[147.02823551  34.11861067 -96.99663363]
[147.75041371  34.05111944 -97.6837655 ]
[147.83736714  34.06961122 -97.72668801]
[148.44474085  33.65335497 -98.85967384]
[148.88955757  34.08508644 -98.56847382]
[147.74931797  3

[ 149.20686041   32.97586428 -100.53787363]
[147.74000881  33.17622908 -99.00005913]
[148.92224904  33.60024052 -99.33900656]
[147.79775179  33.03204174 -99.2664692 ]
[148.43922437  33.11069913 -99.6829327 ]
[148.72182431  33.51420641 -99.30312372]
[ 148.86162011   33.03274013 -100.15783718]
[ 150.04653948   32.98347708 -101.24463606]
[ 149.48073998   33.18553345 -100.4479821 ]
[147.7129525   32.67561465 -99.73558742]
[147.98184536  32.87360917 -99.66046601]
[147.51722129  32.88358641 -99.25773216]
[ 149.03954104   32.96539703 -100.41180678]
[ 149.60179589   32.98752347 -100.85674424]
[ 149.09472604   33.13269236 -100.20171466]
[146.8515256   32.9572896  -98.59629857]
[147.39417596  33.05906846 -98.89071568]
[147.89813848  32.83571565 -99.64791903]
[ 149.22050424   33.0070466  -100.50152694]
[ 147.85309608   32.46937459 -100.1657383 ]
[ 148.87807087   32.70294865 -100.67710978]
[ 148.85485607   32.70344649 -100.65660146]
[148.20111193  32.92472439 -99.76652612]
[ 149.55880932   32.3778

[148.67406013  33.14693851 -99.82486349]
[147.90478135  33.28807006 -98.96722507]
[ 149.31647079   33.14703215 -100.36768704]
[148.34052414  32.95252354 -99.84124294]
[147.34328812  33.15174646 -98.70886723]
[148.72214721  33.91510746 -98.68998059]
[147.40388442  33.68925149 -97.94783909]
[147.00818334  33.14458958 -98.44379487]
[147.76179259  33.36389732 -98.73386343]
[147.50243984  33.44458607 -98.39797866]
[ 149.46913562   33.36263831 -100.16503673]
[148.19988813  33.1480129  -99.42571141]
[149.55809535  33.5454575  -99.95833135]
[148.42611381  33.37206098 -99.27327261]
[ 148.9846703    33.06149061 -100.21784405]
[148.05507626  33.00674428 -99.51950806]
[147.17382467  33.28876088 -98.36295906]
[148.60109132  33.35770451 -99.44143838]
[147.31849961  33.31713325 -98.43907086]
[147.02623327  33.06847541 -98.57302592]
[148.27943287  33.07929373 -99.59686355]
[148.88611236  33.30584392 -99.75998357]
[ 148.89841442   32.80762205 -100.53399149]
[ 149.18373717   33.20082277 -100.17238782]
[

[148.12447741  33.56350605 -98.73098643]
[147.28141391  34.08282631 -97.25489625]
[148.47523119  34.09265918 -98.2145862 ]
[146.9367256   33.58385477 -97.72561247]
[148.33393677  33.50253482 -98.99756933]
[147.48543635  34.16673768 -97.29356778]
[147.53683269  33.63783363 -98.13427271]
[145.77943389  33.75615905 -96.53676339]
[146.22758975  33.57404806 -97.16640574]
[145.71137972  33.52819139 -96.82021693]
[146.95133595  33.80277057 -97.40882269]
[146.50795233  33.28640738 -97.82247716]
[147.91925921  33.51931299 -98.6283949 ]
[148.29838058  33.60078235 -98.81835873]
[147.60878775  33.43635219 -98.497947  ]
[146.15651455  32.99128646 -97.9769116 ]
[146.5592962   33.62260618 -97.36153742]
[147.04807091  34.19162874 -96.90290707]
[145.73234079  33.75437471 -96.50188278]
[146.73259656  33.67405383 -97.42472581]
[146.41156611  33.8443557  -96.91129145]
[148.05410911  33.55191354 -98.69037325]
[147.49512045  33.55056733 -98.23189281]
[147.21735612  33.93075229 -97.43201819]
[146.31289675  3

[146.88291303  33.21864217 -98.22987672]
[146.25777987  33.01110925 -98.02982327]
[146.58214945  33.08483486 -98.1843743 ]
[145.54616817  32.55944656 -98.12143855]
[146.37270052  32.11312522 -99.46438059]
[145.41632296  33.04449368 -97.2990899 ]
[146.09684354  32.33935933 -98.89892839]
[145.5069751   32.46709203 -98.22620969]
[144.89085476  32.32895917 -97.92948358]
[144.28936345  31.91877668 -98.04366964]
[145.99303674  31.95314797 -99.38808234]
[146.69750905  32.09538103 -99.76118886]
[145.19047675  31.96876075 -98.70402663]
[145.61022886  32.51055387 -98.24600693]
[146.35439279  32.49787685 -98.87469326]
[145.47440973  32.2241999  -98.55901266]
[145.16718198  32.08272156 -98.51685792]
[144.54470764  32.25263075 -97.76160328]
[142.89040151  32.29279302 -96.3831666 ]
[146.08266951  32.34891441 -98.87303263]
[ 147.05036559   31.99244997 -100.21103892]
[147.11062117  32.37316555 -99.68870292]
[146.43925225  32.70915841 -98.62894781]
[146.81827829  33.4587414  -97.81695057]
[145.12942606

[147.38662648  32.33167313 -99.98212284]
[145.92197854  32.4375351  -98.60920327]
[ 148.02946031   32.23240992 -100.67437543]
[146.44578224  32.30006962 -99.24565504]
[146.86530047  32.31666742 -99.56911875]
[147.05272973  32.50106042 -99.44806156]
[ 147.73781848   32.39536157 -100.18086332]
[146.97924068  32.34638183 -99.61940556]
[ 147.91601302   32.1691227  -100.67431447]
[145.89593307  31.83912906 -99.47720102]
[146.53087514  32.40166933 -99.16417421]
[146.79232731  32.09489138 -99.84106123]
[ 147.40820417   32.29393922 -100.05717757]
[146.84430923  32.05631464 -99.94239136]
[ 147.64005172   31.86223666 -100.90530488]
[ 146.9359892    31.97810371 -100.13661931]
[146.64726612  31.93724302 -99.95617318]
[146.16881656  31.95357486 -99.5331988 ]
[145.66627543  31.52682876 -99.75034468]
[ 145.65099483   31.21704675 -100.1971346 ]
[ 146.99535634   31.85012927 -100.37881167]
[ 146.42079738   31.66965077 -100.16709674]
[146.16911205  31.76844416 -99.80941558]
[146.51494314  32.73841166 -98

[147.05061203  33.18178048 -98.42273593]
[147.45454621  33.00963718 -99.01531222]
[146.72406114  32.82213507 -98.69409089]
[147.5384867   32.6412594  -99.64166332]
[146.37625921  32.35016183 -99.11330656]
[145.61863857  32.5469829  -98.19889714]
[146.51593597  32.22191343 -99.4206689 ]
[145.35216413  32.6049912  -97.89652484]
[145.46701503  32.14031803 -98.67706454]
[145.46164408  32.69209701 -97.85654621]
[147.3056632   32.49182636 -99.67278356]
[147.84159877  32.80849323 -99.6419027 ]
[146.69590551  32.79607695 -98.70995932]
[147.08120212  32.16586053 -99.97603635]
[147.56791629  32.5516532  -99.80173132]
[ 148.50487211   32.0196408  -101.40348061]
[ 148.74950404   32.39646567 -101.03683266]
[ 149.47398376   32.52144866 -101.4660259 ]
[ 149.05083507   32.41140095 -101.27176201]
[ 148.37613451   32.59214046 -100.42057683]
[ 148.07548632   32.69750379 -100.00655392]
[ 149.74745731   32.47865992 -101.7680533 ]
[ 148.91044183   31.82099874 -102.05629348]
[ 148.87940382   32.39221528 -101

[ 147.42386515   32.25168382 -100.13411888]
[147.10333729  32.19166179 -99.95574975]
[ 147.5622694    32.09837949 -100.48229639]
[ 148.95327656   32.16177902 -101.57090995]
[ 148.23654446   32.62715464 -100.24925759]
[ 148.00911713   32.57885656 -100.13096031]
[146.63366444  32.51126758 -99.08517257]
[146.65747231  32.61145178 -98.954819  ]
[ 148.08551864   32.28451984 -100.64270929]
[147.20676243  32.43893053 -99.66993203]
[146.39423553  32.64157934 -98.69290251]
[147.24119368  32.70469305 -99.29822783]
[145.5346145   32.8359872  -97.70280855]
[146.91070076  33.33536402 -98.07741734]
[147.32116657  32.91148829 -99.05288463]
[146.00779962  33.10572506 -97.68586319]
[146.80338619  32.57335803 -99.13254508]
[145.34240246  32.27427473 -98.37713282]
[145.74138421  32.33943078 -98.60686778]
[146.02689989  32.12799777 -99.1558998 ]
[146.86662729  32.64461189 -99.07797843]
[145.83275084  32.53794398 -98.38700874]
[146.02929018  32.46835131 -98.65139501]
[146.60220389  31.96850365 -99.87171103

[145.72050827  31.77608062 -99.42553334]
[146.33776339  32.56164743 -98.76580522]
[147.29797742  32.7935731  -99.21143569]
[146.23030866  32.9727553  -98.06461535]
[147.15510683  32.93768621 -98.8760086 ]
[ 148.86222143   32.80662124 -100.50479319]
[145.95736324  32.38929284 -98.70994903]
[147.22818585  32.49699762 -99.60033041]
[ 148.3590072    32.73707147 -100.18517674]
[146.35134665  32.24889749 -99.24392105]
[146.10561901  32.00932972 -99.39770419]
[ 147.36098041   31.89685769 -100.61668303]
[ 147.31197284   32.1548898  -100.18615447]
[145.24298491  31.92345022 -98.81393325]
[ 147.92639456   31.96882144 -100.98706545]
[146.01457631  31.77253272 -99.67473532]
[146.03859427  31.97700953 -99.39030392]
[ 147.01440669   31.9650439  -100.22205618]
[146.80405661  32.19090352 -99.70681658]
[145.93903803  32.45553604 -98.59643219]
[ 147.53289095   32.11324073 -100.43503911]
[144.73569057  31.72527747 -98.69034368]
[146.17790044  31.95081808 -99.54485012]
[ 146.91751364   32.01434312 -100.06